# Generated by Django 4.1.3 on 2022-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kompaniya malumoti',
            },
        ),
    ]
