# Generated by Django 4.1.3 on 2022-11-17 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Tavsif'),
        ),
    ]
