# Generated by Django 4.1.3 on 2022-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0003_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yetkaziberish xizmati',
            },
        ),
    ]
