# Generated by Django 4.1.3 on 2022-11-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0004_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Kontakt',
            },
        ),
    ]
