# Generated by Django 4.1.3 on 2022-11-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0008_location_remove_contact_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='comment/image')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Sayt uchun koment',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
