# Generated by Django 4.1.3 on 2022-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0009_comment_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='media/comment/image'),
        ),
    ]
