# Generated by Django 4.1.3 on 2022-11-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='braches')),
            ],
            options={
                'verbose_name': 'Filiallar',
            },
        ),
    ]
