# Generated by Django 4.1.3 on 2022-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0013_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Filial Tavsifi',
            },
        ),
    ]
