# Generated by Django 4.1.3 on 2022-11-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0014_branchdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdetail',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics_about.branches'),
        ),
    ]
