# Generated by Django 4.1.3 on 2022-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_about', '0015_branchdetail_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
