# Generated by Django 4.1.3 on 2022-11-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Brendlar',
            },
        ),
        migrations.CreateModel(
            name='Caregory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "To'plam",
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='menucategory')),
            ],
            options={
                'verbose_name': 'Menyu Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics_main.caregory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Ishlab chiqaruvchi')),
                ('vendor_code', models.CharField(max_length=10, verbose_name='Sotuvchi kodi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlovha')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabrics_main.brand')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabrics_main.caregory')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabrics_main.collection')),
                ('menucategoriy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabrics_main.menucategory')),
            ],
        ),
        migrations.AddField(
            model_name='caregory',
            name='menucategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics_main.menucategory'),
        ),
    ]
