# Generated by Django 4.1.3 on 2022-11-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregoriy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('menucategoriy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics_main.menucategoriy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics_main.caregoriy')),
            ],
            options={
                'verbose_name': 'Kategoriya',
            },
        ),
    ]
