# Generated by Django 4.1.3 on 2022-12-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
