# Generated by Django 4.1.3 on 2022-11-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0002_caregoriy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregoriy',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics_main.caregoriy'),
        ),
    ]
