# Generated by Django 4.1.5 on 2023-01-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0009_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='_selling_price',
        ),
    ]
