# Generated by Django 4.1.5 on 2023-01-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0010_rename_selling_price_product__selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_selling_price',
        ),
    ]
