# Generated by Django 4.1.5 on 2023-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0011_remove_product__selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
